services:
  postgres:
    image: postgres:16
    container_name: h1_canchas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: h1_canchas
    ports:
      - "5432:5432"
    volumes:
      - h1_canchas_postgres_data:/var/lib/postgresql/data

volumes:
  h1_canchas_postgres_data:
